version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=codeworks-db
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
