version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
    # Create a .env file with these variables
    # To check their values run `docker-compose config`
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
